### ISSUE TITLE
Use GitHub Action Step for Initial PR Comment

### ISSUE THREAD

**Issue by FyZyX** [FyZyX/review-me#67]
## Description
Replace our code-generated initial comment with a GitHub Action step.

## Tasks
- [x] Research existing GitHub Actions for posting PR comments
- [x] If no suitable action exists, create a step using GitHub CLI
- [x] Update workflow to include this new step before our main action
- [x] Remove initial comment generation from our code

## Benefits
- Simplifies our main action code
- Potentially more reliable comment posting
- Leverages GitHub Actions ecosystem
